---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: nginx
  name: nginx-deploy
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 20%
  template:
    metadata:
      labels: 
        app: nginx
        version: "perl"
      name: nginx-pod
    spec: 
      containers:
        - image: nginx:perl
          name: nginx-container
          ports: 
            - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata: 
  name: nginx-service-np
  labels: 
    app: nginx
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      targetPort: 80
      port: 31000
      name: webport
  selector: 
    app: nginx