---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: Jenkins-rs
  labels:
    cicd: jenkins
spec: 
  minReadySeconds: 5
  replicas: 6
  selector:
    matchLabels: 
      cicd: jenkins
  template:
    metadata:
      name: jenkins-pods
      labels:
        cicd: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts-jdk17
          name: jenkins-container
          ports: 
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"