---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: aws-mysql-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests: 
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod-env
  labels:
    database: mysql
spec:
  containers:
    - image: mysql:8.3.0
      name: mysql-conatiner-env
      envFrom:
       - configMapRef:
           name: mysql-config
       - secretRef:
           name: mysql-secrets
      ports:
        - containerPort: 3306
          name: mysql-port
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
  volumes:
     - name: mysql-volume
       persistentVolumeClaim: 
         claimName: aws-mysql-pvc
         readOnly: false