---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc-cip
  labels:
    app: nginx
spec:
  ports: 
    - port: 32000
      targetPort: 80
  selector: 
    app: nginx
  type: ClusterIP







  