---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-loadbalancer-svc
  labels:
    app: nginx
spec:
  ports: 
    - port: 32000
      targetPort: 80
      name: webport
  selector: 
    app: nginx
  type: LoadBalancer