---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-nordport-svc
  labels:
    app: nginx
spec:
  ports: 
    - port: 32000
      targetPort: 80
      nodePort: 32765
      name: webport
  selector: 
    app: nginx
  type: NodePort
  