---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    app: nginx
  template:
    metadata: 
      name: nginx-pod
      labels:
        app: nginx
        ver: "1.25"
        environment: pre-prod
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
              protocol: TCP 