---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: jenkins
  name: jenkins-deploy
spec:
  minReadySeconds: 10
  replicas: 5
  selector:
    matchLabels:
      app: jenkins
      version: "2.53"
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 20%
  template:
    metadata:
      labels: 
        app: jenkins
        version: "2.53"
      name: jenkins-pod
    spec: 
      containers:
        - image: jenkins/jenkins:2.53
          name: jenkins-container
          ports: 
            - containerPort: 8080