---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: jenkins
  name: jenkins-deploy
spec:
  minReadySeconds: 10
  replicas: 5
  selector:
    matchLabels:
      app: jenkins
      version: "1.625.1"
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 20%
  template:
    metadata:
      labels: 
        app: jenkins
        version: "1.625.1"
      name: jenkins-pod
      spec: 
        containers:
          - image: jenkins:1.625.1
            name: jenkins-container
            ports: 
              - containerPort: 8080
---
apiVersion: v1 
kind: Service
metadata: 
  name: jenkins-service-lb
  labels: 
    app: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 35000
      targetPort: 8080
      name: webport