---
apiVersion: v1 
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    cicd: jenkins
spec:
  containers:
    - name: jenkins-container
      images: jenkins/jenkins:jdk17
      ports:
        - name: jenkins-port
          containerPort: 8080
      readinessProbe:
      httpGet:
        path: /
        port: 8080
      livenessProbe:
      tcpSocket:
        port: 8080