---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: first-cronjob
  namespace: hello-namespace
spec:
  schedule: "25 07 * * 1-5"
  jobTemplate: 
    metadata: 
      name: cron-job
    spec:
      backoffLimit: 5
      template:
        metadata: 
          name: cronjob-pod
          labels:
            app: nginx
            purpose: cron-execution
        spec:
          restartPolicy: OnFailure
          containers:
            - image: alpine:3
              name: cronjob
              command: 
                - sleep
                - 300s
