---
apiVersion: v1
kind: Pod
metadata: 
  name: labels-demo
  labels:
    web: nginx
    version: 1.25
    environment: pre-prod
spec:
  containers:
    - image: nginx:1.25
      name: nginx-1.25
      ports:
        - containerPort: 80
          
---
apiVersion: v1
kind: Pod
metadata: 
  name: labels-demo
  labels:
    web: nginx
    version: 1.24
    environment: pre-prod
spec:
  containers:
    - image: nginx:1.24
      name: nginx-1.24
      ports:
        - containerPort: 80       