---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cicd-rs
  labels:
    app: jenkins
spec:
  minReadySeconds: 5
  replicas: 6
  selector:
    matchLabels: 
      app: jenkins
      purpose: cicd
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
        purpose: cicd
    spec:
      containers:
        - image: jenkins/jenkins:jdk17
          name: cicd
          ports:
            - containerPort: 8080
      initContainers:
        - command: ["ping" ,"-c","4","google.com"]
          image: alpine:3
          name: ping