---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels: 
    app: nginx
    version: "1.25"
  name: nginx-rs
spec:
  minReadySeconds: 5
  replicas: 8
  selector:
    matchLabels: 
      app: nginx
      version: "1.25"
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        version: "1.25"
    spec:
      containers:
        - image: nginx:1.25
          name: nginx
          ports:
            - containerPort: 80